// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Editor struct {
	ID    *string `json:"id,omitempty"`
	Name  string  `json:"name"`
	Games []*Game `json:"games,omitempty"`
}

type EditorInput struct {
	Name string `json:"name"`
}

type Game struct {
	ID              *string   `json:"id,omitempty"`
	Name            string    `json:"name"`
	Genres          []string  `json:"genres"`
	PublicationDate *int      `json:"publicationDate,omitempty"`
	Editors         []*Editor `json:"editors"`
	Studios         []*Studio `json:"studios"`
	Platform        []string  `json:"platform"`
}

type GameInput struct {
	Name            string       `json:"name"`
	Genres          []string     `json:"genres"`
	PublicationDate *int         `json:"publicationDate,omitempty"`
	Platform        []string     `json:"platform"`
	EditorIDs       []string     `json:"editorIDs"`
	StudioIDs       []string     `json:"studioIDs"`
	Editor          *EditorInput `json:"editor"`
	Studio          *StudioInput `json:"studio"`
}

type Games struct {
	Infos   *Infos  `json:"infos,omitempty"`
	Results []*Game `json:"results,omitempty"`
}

type Infos struct {
	Count         int  `json:"count"`
	Pages         int  `json:"pages"`
	NextPage      *int `json:"nextPage,omitempty"`
	PreviousPages *int `json:"previousPages,omitempty"`
}

type Studio struct {
	ID    *string `json:"id,omitempty"`
	Name  string  `json:"name"`
	Games []*Game `json:"games,omitempty"`
}

type StudioInput struct {
	Name string `json:"name"`
}
